package com.taskflow.backend.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import lombok.Data; // Import for automatic Getters/Setters
import lombok.NoArgsConstructor; // Import for the default constructor
import lombok.AllArgsConstructor; // Optional: for a constructor with all arguments

@Entity // Marks this class as a JPA entity (a database table)
@Table(name = "users") // Names the corresponding table 'users'
@Data // Automatically generates all getters, setters, toString(), etc. (Requires Lombok dependency)
@NoArgsConstructor // Generates a constructor with no arguments
@AllArgsConstructor // Generates a constructor with all arguments
public class User {
    
    // PRIMARY KEY: id, automatically generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // ATTRIBUTES (Columns) based on your plan
    private String name;
    private String email;
    private String password;
    private String role; // e.g., 'ADMIN' or 'MEMBER'
}